### ISSUE TITLE
Version installed by gem is out of date

### ISSUE THREAD

**Issue by toomanytims** [imeyer/simple-graphite#5]
Heya, Not being an expert with the underlying mechanisms of the 'gem' distribution system, I'm not quite sure where to ask this..  However, the version of simple-graphite that is is currently available  via 'gem install simple-graphite', currently, seems to be out of date?

The send_metrics function doesn't appear to exist, so I'm guessing that it represents an older version of the library.

Is this something that you maintain or have any level of control over?

**Comment by imeyer** [comment]
Hi @toomanytims, I do maintain control.. I'm away in a place with not great internet access, when I return home on the 18th of February, I'll get this sorted out for you. :)

**Comment by pdf** [comment]
This should probably be closed now.

**Comment by imeyer** [comment]
Ah good catch! :smile:
